#+title: Manifeste EIG

# Source : [[https://bimestriel.framapad.org/p/eig-introduction]]

*Sous-titre* : Manuel d'utilisation des compétences numériques dans
l'administration.

* Introduction

** [Qui nous sommes]

Nous sommes designers, datascientistes, développeurs.  Nous venons de
la recherche, des start-ups ou de l'entreprise traditionnelle.  Nous
avons des parcours d'ingénieurs ou de sciences humaines.  Notre goût
pour les technologies du Web s'est mêlé tôt à notre sens civique, et
nous consacrons du temps à des associations ou à des projets de biens
communs numériques.

Le programme « Entrepreneur·e d'intérêt général », porté par la
mission Etalab de la DINSIC, nous a permis de mettre nos compétences
techniques au service de l'administration publique pendant dix mois,
au contact d'agents publics désireux de transformer leur utilisation
de l'informatique.  Nous avons mis en commun nos expériences et nous
avons convergé vers quelques principes qui nous paraissent pouvoir
guider la transformation de l'administration par le numérique.

** [Quel message nous portons - les principes]

Voici la vision que nous proposons : des projets informatiques de
taille réduite, avec des composants les plus génériques possibles, et
une approche par amélioration continue ; des projets s'appuyant sur
des ressources internalisées pour permettre de nouvelles formes de
mobilisation et d'ouverture.

[Ordre suggéré pour les sections : réduire ; rendre générique ;
améliorer ; internaliser ; mobiliser ; ouvrir.]

** [À qui s'adresse ce manifeste]

Ce manifeste s'adresse en priorité aux décideurs politiques et aux
agents publics en charge de la transformation des politiques publics
par le numérique.  Plus largement, il vise tous les citoyens ayant,
comme nous, à coeur d'améliorer le service publique, et s'intéressant
aux nouvelles possibilités offertes par les outils numériques.

** [Notre objectif en publiant ce manifeste]

[Avoir un discours qui sort du "solutionisme"]

Nous ne croyons pas que le numérique soit une « solution » : notre
perspective n'est pas celle de l'efficacité administrative mais celle
du sens que les agents publics trouvent dans leurs missions, missions
dont l'évaluation revient aux citoyens-usagers.  Et nous croyons que
la transformation numérique est le meilleur moyen de redonner du sens
à cette action, en créant plus de lien entre l'administration et ses
citoyens-usagers

** [Ce que ce manifeste n'est pas ?]
   
