#+title: Limiter : réduire le périmètre fonctionnel, la durée et donc les risques

* Idée générale 

La taille des projets informatiques est inversement proportionnelle à
leur chance d'aboutir. Or, il n'est pas rare de voir, dans
l'administration, des projets informatiques de plusieurs dizaines de
millions d'euros et la tendance est à l'augmentation de la taille de
ces projets [FIXME: référence ?].

* Diagnostic : 

** Grande taille humaine

- Plus on ajoute de personnes dans un projet, plus le coût de
  coordination augmente.
- Risque de perte du lien utilisateur

** Grande taille temporelle

- Grand temps d'itération. Risque de ne pas répondre au besoin
  utilisateur.
- Risque de frustration devant le temps avoir d'avoir les premiers
  résultats
- Temps long dans le domaine de l'informatique où le rythme
  d'évolution est rapide. Risque d'obsolescence des technologies
  utilisées

** Grande taille financière

- Escalade de l'engagement, il est difficile d'arrêter un projet voué
  à l'échec : on a déjà investi X millions dans ce nouveau système on
  ne peut plus reculer

* Proposition d'avenir : "Small is beautiful"

Ce n'est pas simple, mais casser un gros projet en de plus petit
projets incrémentales fonctionnels et valorisables indépendamment.

Pratiquer le pre-mortem : imaginer toutes les raisons qui ferait qu'un
projet ne fonctionnerait pas.

[bzg: Attention à ne pas trop verser du côté de la "composition".]

* Exemple de projet bien délimité

Les musées doivent gérer des collections d'objets et les exposer via
des sites web.  Ces problématiques sont parfois abordées via un seul
outil, servant à la fois à l'inventaire des objets et à la diffusion
des données qui les concernent (images, descriptions, etc.)

Le défi EIG 2 du Mobilier national s'est concentré sur la conception
et le développement d'une interface de diffusion et de valorisation.
La problématique de la gestion des collections a été laissée de côté,
et l'interface de diffusion a été conçue pour être paramétrable et
se connecter à d'autres outils.

Les contre-parties de cette ambition limitée : les EIG ont exploré
à fond la question des publics et ont proposé un outil que d'autres
musées pourront réadapter à leurs besoins.

   

