#+title: Limiter : réduire le périmètre fonctionnel, la durée et donc les risques

* Idée générale 

La taille des projets informatiques est inversement proportionnelle à
leur chance d'aboutir. Or, il n'est pas rare de voir, dans
l'administration, des projets informatiques de plusieurs dizaines de
millions d'euros et la tendance est à l'augmentation de la taille de
ces projets [FIXME: référence ?].

* Diagnostic : 

En rajoutant des parties prenantes à un projet on ajoute mécaniquement
une complexité managériale très coûteuse sur le long terme. La multiplication
des interlocuteurs engendre un risque important de perdre le lien avec l'
utilisateur final.

Plus un projet grandit, plus il devient compliqué d'être réactif,
le temps entre chaque itération augmentant lui aussi pour de
multiples raisons (coordination, sécurité, politique interne...). Il est
alors plus difficile d'être certain de répondre au mieux aux besoins
utilisateurs. Des frustrations internes apparaissent également puisque le 
temps nécessaire pour voir le résultat du travail accompli augmente.
A l'heure où les technologies et les méthodes évoluent très vite 
dans l'informatique, en allongeant en parallèle les cycles de 
production on prend le risque d'utiliser des technologies et méthodes
obsolètes compromettant ainsi l'avenir de la solution développée.

Enfin, un projet important qui aura nécessité des sommes conséquentes sera
d'autant plus difficile à abandonner malgré des résultats médiocres constatés. 
Ce phénomène bien connu d'escalade de l'engagement, empêche l'analyse objective 
d'un projet et conduit à prendre de mauvaises décisions.

Le récent abandon du système global de gestion de resources humaines 
"SIRHEN" du minitère de l'Education Nationale, après près de 10 années
de développement pour un coût total de 320 millions d'euros, est 
malheureusement le parfait exemple d'un projet qui est devenu par sa taille 
au fil du temps ingérable. 

* Proposition d'avenir : "Small is beautiful"

Ce n'est pas simple, mais casser un gros projet en de plus petit
projets incrémentales fonctionnels et valorisables indépendamment.

Pratiquer le pre-mortem : imaginer toutes les raisons qui ferait qu'un
projet ne fonctionnerait pas.

[bzg: Attention à ne pas trop verser du côté de la "composition".]

* Exemple de projet EIG scalable

Le logiciel de diffusion des collections du défi Gobelins.
   

