* Ouvrir

Source : [[https://bimestriel.framapad.org/p/eig-ouvrir]]

Propriétaire / opaque vs Open source / transparence

L'ouverture des algorithmes et données est une obligation pour les aux administrations qui permet de XXX
Mais aussi -> 
renforce également leur légitimité par la médiation qu'elles mettent en place,
leur efficacité par les contributions extérieures et la réutilisation de leurs productions 
leur utilité publique par une plus grande symétrie d'information.





Algo explicable, lisible, accessible, reproductible   

Permettre de comprendre les productions de façon claire, précise. 


-> médiation, ouverture code, ouverture données



-> production de données, diffusion du savoir/ des ressources



-> contributions extérieures (github/wikipédia/hackatons etc.), rayonnement

Exemples : 
wikipedia ou hackathon
Logiciel libre / social connect




transparence :
    J’informerai de façon compréhensible et précise toutes les parties prenantes sur les finalités, les modalités et les implications potentielles de mon utilisation des données.
    
    communiquer, ou sinon rappeler aux équipes compétentes, la nécessité de communiquer auprès des personnes concernées, l’usage qui sera fait de leurs données, de la façon la plus claire, explicite et transparente possible.






Construire, accompagner et diffuser des outils et méthodes explicites et réutilisables.

Concrétement :
    - logiciel libre
    - ouverture des données
    -interface lisible accessible
    - transparence / symétrie / explicabilité


L’ouverture c’est de l’avenir
Ouverture vers le futur

Favoriser 
Participer 
Augmenter
Contribuer


Transparence des algos, des usages, des origines

Explicabilité

Ouverture des contenus
Diffusion 
Partage
Réutilisation
Accessibilité
Médiation
Compréhension
Lisibilité
Symétrie (le calculant et calculé puissent discuter de la mm chose)
